# Generated by Django 4.0.3 on 2022-03-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
